default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: personal-site_development

test:
  <<: *default
  database: personal-site_test

production:
  adapter: postgresql
  database: personal-site_production
  username: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
